spring:
  application:
    name: ConfessionWallBack
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ai.tordor.top:50358/confession_wall?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: confession_wall
    password: confession_wall

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: postIsDelete #逻辑删除的实体类字段
      logic-delete-value: 1 #逻辑删除
      logic-not-delete-value: 0 #逻辑未删除
logging:
  level:
    com:
      sanding:
        confessionwallback:
          mapper: debug
          service: info
          controller: info
jwt:
  # 设置jwt签名加密时使用的秘钥
  admin-secret-key: confessionwallback
  # 设置jwt过期时间
  admin-ttl: 7200000
  # 设置前端传递过来的令牌名称
  admin-token-name: token
  user-secret-key: confessionwallback
  user-ttl: 7200000
  user-token-name: authentication
wechat:
  appid: null
  secret: null