spring:
  application:
    name: ConfessionWallBack
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/confession_wall?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: confession_wall
    password: confession_wall

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true